-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgf4QMO1wXBAWGK4R2yfcSO3/dF+0ZADEOaCWkKaCUHzygCgYIKoZIzj0DAQehRANCAARyitB6QpAVEqy+rZUf7YOUjRwoZXH8W9wZfoskC8AzLThDVzp/6TdpF26SUsMvXAbx7yE1f06OMD8A6cEirLXQ
-----END PRIVATE KEY-----